@RopDemo_HostAddress = http://localhost:5004
### Create an account using iperative code
POST {{RopDemo_HostAddress}}/imperative/accounts
Content-Type: application/json

{
  "FirstName": "Aarjan",
  "LastName": "Meirink",
  "EmailAddress": "aarjan.meirink@rtl.nl",
  "TelephoneNumber": "0643545143"
}

### Get all the accounts using imperative code
GET {{RopDemo_HostAddress}}/imperative/accounts
Accept: application/json

### Get the account using imperative code
GET {{RopDemo_HostAddress}}/imperative/accounts/cf997d2c-711e-4110-b1ff-c509c9af6cbb
Accept: application/json

###
